# Generated by Django 4.2.29 on 2026-03-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_course_mapping", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productcoursemapping",
            old_name="primayr_mapping",
            new_name="primary_mapping",
        ),
    ]
